Fix ijview to work with individual JAR libs
Either loci_plugins.jar or loci_tools.jar (but not both)
needs to be on the classpath.

diff --git a/tools/ijview b/tools/ijview
--- a/tools/ijview
+++ b/tools/ijview
@@ -25,6 +25,20 @@ then
     echo ""
     exit 3
   fi
+  if [ -e "$SCIFIO_JAR_DIR/loci_plugins.jar" ]
+  then
+    SCIFIO_CP="$SCIFIO_CP:$SCIFIO_JAR_DIR/loci_plugins.jar"
+  elif [ ! -e "$SCIFIO_JAR_DIR/loci_tools.jar" ]
+  then
+    # Libraries not found; issue an error
+    echo "Required JAR libraries not found. Please download:"
+    echo "  loci_tools.jar"
+    echo "from:"
+    echo "  http://www.loci.wisc.edu/bio-formats/downloads"
+    echo "and place in the same directory as the command line tools."
+    echo ""
+    exit 4
+  fi
 fi
 
 SCIFIO_PROG=loci.plugins.in.Importer \
