Use SCIFIO_JAR_DIR var for directory with JAR libs
This gives us a bit more flexibility in exactly where the JAR files
live. When running from a git working copy, the artifacts directory is
auto-detected and used as the SCIFIO_JAR_DIR.

diff --git a/tools/ijview b/tools/ijview
--- a/tools/ijview
+++ b/tools/ijview
@@ -12,13 +12,23 @@ SCIFIO_DIR=`dirname "$0"`
 
 source "$SCIFIO_DIR/config.sh"
 
-if [ -z "$SCIFIO_DEVEL" ] && [ ! -e "$SCIFIO_DIR/ij.jar" ]
+if [ -z "$SCIFIO_DEVEL" ]
 then
-  echo "Required JAR libraries not found. Please download:"
-  echo "  ij.jar"
-  echo "from:"
-  echo "  http://imagej.nih.gov/ij/upgrade/"
-  echo "and place in the same directory as the command line tools."
-else
-  SCIFIO_PROG=loci.plugins.in.Importer SCIFIO_CP="$SCIFIO_DIR/ij.jar" "$SCIFIO_DIR/launch.sh" "$@"
+  # Developer environment variable unset; add JAR libraries to classpath.
+  if [ -e "$SCIFIO_JAR_DIR/ij.jar" ]
+  then
+    SCIFIO_CP="$SCIFIO_JAR_DIR/ij.jar"
+  else
+    # Libraries not found; issue an error
+    echo "Required JAR libraries not found. Please download:"
+    echo "  ij.jar"
+    echo "from:"
+    echo "  http://imagej.nih.gov/ij/upgrade/"
+    echo "and place in the same directory as the command line tools."
+    echo ""
+    exit 3
+  fi
 fi
+
+SCIFIO_PROG=loci.plugins.in.Importer \
+  SCIFIO_CP="$SCIFIO_CP" "$SCIFIO_DIR/launch.sh" "$@"
